repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^pkg/.+\.json$
      - id: file-contents-sorter
        files: ^\.gitignore
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: ^pkg/.+\.json$
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: text-unicode-replacement-char

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: ^pkg/.+\.json$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

  - repo: https://github.com/DiverseStardewValley/Scripts
    rev: 0.1.1
    hooks:
      - id: remove-blank-lines
        files: ^src/.+\.json$
      - id: minify-json
        args: ["--input=src", "--output=pkg", "--copy=(manifest|modded_config)"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.4
    hooks:
      - id: check-github-workflows

ci:
  autoupdate_schedule: monthly
